# Generated by Django 4.2.30 on 2026-04-17 01:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.FloatField(help_text='Nitrogen (N) ratio in soil')),
                ('phosphorus', models.FloatField(help_text='Phosphorus (P) ratio in soil')),
                ('potassium', models.FloatField(help_text='Potassium (K) ratio in soil')),
                ('temperature', models.FloatField(help_text='Temperature in °C')),
                ('humidity', models.FloatField(help_text='Relative humidity (%)')),
                ('ph', models.FloatField(help_text='Soil pH value')),
                ('rainfall', models.FloatField(help_text='Rainfall in mm')),
                ('predicted_crop', models.CharField(max_length=100)),
                ('confidence_score', models.FloatField(blank=True, help_text='Max class probability from Random Forest (0-1)', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_id', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Crop Prediction',
                'verbose_name_plural': 'Crop Predictions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiseasePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Uploaded plant leaf image', upload_to='disease_images/%Y/%m/')),
                ('predicted_disease', models.CharField(max_length=200)),
                ('confidence_score', models.FloatField(blank=True, help_text='Softmax probability for the top predicted class (0-1)', null=True)),
                ('top_3_predictions', models.JSONField(blank=True, help_text='List of {label, confidence} for the top-3 classes', null=True)),
                ('plant_name', models.CharField(blank=True, max_length=100)),
                ('disease_name', models.CharField(blank=True, max_length=100)),
                ('is_healthy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_id', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Disease Prediction',
                'verbose_name_plural': 'Disease Predictions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_crop_preds', models.PositiveIntegerField(default=0)),
                ('total_disease_preds', models.PositiveIntegerField(default=0)),
                ('most_predicted_crop', models.CharField(blank=True, max_length=100)),
                ('most_detected_disease', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant (AgriBot)'), ('system', 'System')], max_length=16)),
                ('content', models.TextField()),
                ('model_used', models.CharField(blank=True, help_text='LLM model tag returned by Ollama (e.g. llama3.2-vision)', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('related_disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='core.diseaseprediction')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['session_id', 'created_at'],
            },
        ),
    ]
