# Generated by Django 4.2.30 on 2026-04-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='model_used',
            field=models.CharField(blank=True, help_text='LLM model tag returned by Ollama (e.g. moondream)', max_length=100),
        ),
    ]
